#!/bin/bash

# list of all the input files (e.g. MAR netcdf output)
files=(../hydroflow/ICE.201[1,2]*)

# this just counts how many files there are
export n_files=${#files[@]}

# netcdf file with flow directions, for now in "ANSWERS" format (cf. files_mod > setup_grid)
export directions_file="../hydroflow/MAR32_fdir.nc"

# if out_file is given, all discharge output will be written to one continuous netcdf file
# of the given name
# otherwise, there will be one output file for each input file, with the name generated from 
# the input file name with the part before the first '.' replaced by 'DIS'
# THIS MAY BREAK depending on the input file names, cf. files_mod > file_name
export out_file="discharge.nc"

# file to save or retrieve grid information from
# if it exists, it will be used and the files_mod > setup_grid routine is not called
# if it doesn't exist, if will be generated by setup_grid
export grid_file="grid.nc"

# if test_mode is set and > 0, the number gives the number of timesteps added to the 
# end of the simulation with zero runoff being added to the cells, so that all water
# can "drain" through the network (I use this to see if water volume is conserved)
# export test_mode=1000

# this is the actual run command - the list of files is read from stdin
echo $(printf "'%s' " "${files[@]}") | ./driver